// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://vspullgchtzqgdclqjaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzcHVsbGdjaHR6cWdkY2xxamF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4MzIxOTYsImV4cCI6MjA5MDQwODE5Nn0.2rn8yJzlz6YmqPzdEXkkq3tRVwm5nO6DGX2IIVet8SQ";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);